### ISSUE TITLE
wasm-trace gives "bad interpreter: No such file or directory" message

### ISSUE THREAD

**Issue by tareq97-zz** [wasm3/wasm-trace#1]
I have installed wasm-trace in my system. But when I am trying to run it getting bad interpreter: No such file or directory issue.

Steps 

1. Install wasm-trace.

2. wasm-trace -ELM ./test.wasm - on execution of this command getting below mentioned error
bash: /usr/local/bin/wasm-trace: node: bad interpreter: No such file or directory

I am using OS - Ubuntu 19.10. Is this why I am getting the issue?

**Comment by vshymanskyy** [comment]
This is probably because it uses a shebang with direct `node` reference:
https://github.com/wasm3/wasm-trace/blob/8f1aa89e811e221a83a89a6de806599d8df6f0cd/wasm-trace.js#L1

What happens, if you run `node` command?
Also, you may try setting up the latest Node.js through `nvm`: https://github.com/nvm-sh/nvm
